export const fakeTransactions = [
  {
    id: "1",
    title: "Zakupy",
    category: "Jedzenie",
    dateTime: "2022-05-30",
    sign: "+",
    partner: "Lidl Polska",
    value: "200.00",
  },
  {
    id: "2",
    title: "Zakupy",
    category: "Zdrowie i uroda",
    dateTime: "2022-05-30",
    sign: "-",
    partner: "Hebe",
    value: "223.50",
  },
  {
    id: "3",
    title: "Wejście do klubu",
    category: "Rozrywka",
    dateTime: "2022-05-30",
    sign: "+",
    partner: "Super Klub",
    value: "20.00",
  },
  {
    id: "4",
    title: "Dotacja na fundację",
    category: "Inne",
    dateTime: "2022-05-30",
    sign: "+",
    partner: "SiePomaga.pl",
    value: "1200.00",
  },
  {
    id: "1",
    title: "Zakupy",
    category: "Jedzenie",
    dateTime: "2022-05-30",
    sign: "+",
    partner: "Lidl Polska",
    value: "200.00",
  },
  {
    id: "2",
    title: "Zakupy",
    category: "Zdrowie i uroda",
    dateTime: "2022-05-30",
    sign: "-",
    partner: "Hebe",
    value: "223.50",
  },
  {
    id: "3",
    title: "Wejście do klubu",
    category: "Rozrywka",
    dateTime: "2022-05-30",
    sign: "+",
    partner: "Super Klub",
    value: "20.00",
  },
  {
    id: "4",
    title: "Dotacja na fundację",
    category: "Inne",
    dateTime: "2022-05-30",
    sign: "+",
    partner: "SiePomaga.pl",
    value: "1200.00",
  },
];
export const fakeUsers = [
  {
    id: "1",
    login: "jano29",
    name: "Jon",
    surname: "User",
    permission: "user",
  },
  {
    id: "2",
    login: "anna123",
    name: "Anna",
    surname: "Normalna-Userka",
    permission: "user",
  },
  {
    id: "3",
    login: "raf22",
    name: "Andrei",
    surname: "Adminov",
    permission: "admin",
  },
];
export const fakeCategories = [
  { id: "1", name: "jedzenie" },
  { id: "2", name: "media" },
  { id: "3", name: "pozostałe opłaty " },
  { id: "4", name: "zdrowie i uroda" },
  { id: "5", name: "rozrywka" },
  { id: "6", name: "inne" },
];
