export const fakeTransactions = [
  {
    key: "1",
    title: "Zakupy",
    category: "Jedzenie",
    dateTime: "2022-04-30",
    sign: "+",
    partner: "Lidl Polska",
    value: "200.00",
    userID: "uuid",
  },
  {
    key: "2",
    title: "Zakupy",
    category: "Zdrowie i uroda",
    dateTime: "2022-05-30",
    sign: "-",
    partner: "Hebe",
    value: "223.50",
    userID: "uuid",
  },
  {
    key: "3",
    title: "Wejście do klubu",
    category: "Rozrywka",
    dateTime: "2022-05-30",
    sign: "+",
    partner: "Super Klub",
    value: "20.00",
    userID: "uuid",
  },
  {
    key: "4",
    title: "Dotacja na fundację",
    category: "Inne",
    dateTime: "2022-05-30",
    sign: "+",
    partner: "SiePomaga.pl",
    value: "1200.00",
    userID: "uuid",
  },
];
export const fakeUsers = [
  {
    key: "1",
    email: "email@email.com",
    login: "jano29",
    userName: "Jon",
    surname: "User",
    permission: "user",
    isActive: "true",
    password: "Abc123",
  },
  {
    key: "2",
    email: "email@email.com",
    login: "anna123",
    userName: "Anna",
    surname: "Normalna-Userka",
    permission: "user",
    isActive: "true",
    password: "Abc123",
  },
  {
    key: "3",
    email: "email@email.com",
    login: "raf22",
    userName: "Andrei",
    surname: "Adminov",
    permission: "admin",
    isActive: "true",
    password: "Abc123",
  },
];

export const fakeCategories = [
  { key: "1", title: "jedzenie" },
  { key: "2", title: "media" },
  { key: "3", title: "pozostałe opłaty " },
  { key: "4", title: "zdrowie i uroda" },
  { key: "5", title: "rozrywka" },
  { key: "6", title: "inne" },
];
